### ISSUE TITLE
OpenGL exception while trying to run the resolver

### ISSUE THREAD

**Issue by meisterT** [hex539/scoreboard#3]
Running `bazel run scoreboards/resolver --     --url https://www.domjudge.org/demoweb/api/     --groups="NWERC - Eindhoven University of Technology"` gives:

```
Fetching https://www.domjudge.org/demoweb/api/contests...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/state...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/scoreboard...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/judgement-types...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/languages...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/problems...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/groups...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/organizations...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/teams...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/submissions...
Fetching https://www.domjudge.org/demoweb/api/contests/nwerc18/judgements...
Exception in thread "main" java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:322)
	at me.hex539.resolver.ResolverWindow.run(ResolverWindow.java:62)
	at me.hex539.resolver.Executive.main(Executive.java:64)
```

btw. all the example command lines need to be updated since we updated our demoweb instance recently. Also the `resolver` from the end of this command line needs to be removed:
https://github.com/hex539/scoreboard/tree/master/scoreboards/resolver

**Comment by hex539** [comment]
Your command works for me on Ubuntu 18.04 LTS and Debian unstable. Can you let me know what OS you're using so I can try it out and have a look at where the actual issue is?

> btw. all the example command lines need to be updated since we updated our demoweb instance recently. Also the resolver from the end of this command line needs to be removed:
https://github.com/hex539/scoreboard/tree/master/scoreboards/resolver

Thanks for flagging

**Comment by meisterT** [comment]
I am using debian buster. The new log after your most recent commit is this:
```
[LWJGL] GLFW_API_UNAVAILABLE error
	Description : GLX: GLX extension not found
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
		me.hex539.resolver.ResolverWindow.run(ResolverWindow.java:57)
		me.hex539.resolver.Executive.main(Executive.java:64)
Failed to create a GLFW window for OpenGL.
```

**Comment by meisterT** [comment]
Well, this is embarrassing. I tried to run `glxgears` which also failed so I debugged a bit and had to remove some nvidia drivers (I don't have an nvidia card)...

**Comment by hex539** [comment]
Perfect, the new error is clear enough about what went wrong. Score one for LWJGL.
